# These are supported funding model platforms

github: [tinovyatkin, walletpass]
open_collective: webpasskit
# issuehunt: # Replace with a single IssueHunt username
custom: ["https://www.paypal.me/fortransfer"]
